{% set name = "Ostrich" %}
{% set version = "21.03.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/usbr/{{ name|lower }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: da5ed2f34254fc75c9d16e541788280dc1a128db1d0608f28ee2eae95f901396
  patches:
    - 0001-fix-makefile.patch

build:
  number: 2
  script:
    - cd make
    - make GCC
    - mkdir -p $PREFIX/bin/
    - cp ./Ostrich $PREFIX/bin/ostrich  # [not win]
    - cp ./Ostrich.exe $PREFIX/bin/Ostrich.exe  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make

test:
  commands:
    - test -f $PREFIX/bin/ostrich  # [not win]
    - ostrich

about:
  home: https://www.civil.uwaterloo.ca/envmodelling/Ostrich.html
  dev_url: https://github.com/usbr/{{ name|lower }}/
  doc_url: https://usbr.github.io/{{ name|lower }}/
  doc_source_url: https://github.com/usbr/{{ name|lower }}/tree/master/docs
  license: GPL-2.0-only
  license_file: LICENSE
  summary: This the conda-forge binary for the Ostrich model calibration tool.

extra:
  recipe-maintainers:
    - Zeitsperre
    - julemai
    - lsmatott
    - dloney
